apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-front
  labels:
    name: guestbook-front
    type: frontend

spec:
  template:
    metadata:
      name: guestbook-front
      labels:
        app: guestbook-front
        type: frontend
    spec:
      containers:
        - name: guestbook
          image: kubernetes/guestbook:v2
          ports:
            - containerPort: 80
  replicas: 2
  selector:
    matchLabels:
      app: guestbook-front
