apiVersion: v1
kind: Service
metadata:
  name: service-guestbook-front
  labels:
    name: service-guestbook-front

spec:
  type: LoadBalancer
  ports:
    - targetPort: 3000
      port: 3000
      nodePort: 30002
  selector:
    app: guestbook-front